require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');

const products = [
  {
    id: 'exam-bed-sheet-10',
    name: 'Disposable Bedsheet',
    sku: 'EX-BED-01',
    price: 18.50,
    priceLabel: '$18.50',
    category: 'Infection Prevention',
    artgNumber: 'ARTG 102934',
    liveStock: 250,
    tagline: '240 × 70 cm · Non-Woven · Dark Blue · 10 Pack',
    description: 'Ensure maximum hygiene and safety for every patient visit with these premium disposable bedsheets designed for examination couches, stretchers, and beds. These single, non-fitted sheets provide an essential protective barrier between your patient and the clinical furniture, significantly reducing the risk of cross-contamination. Constructed from a durable, dark blue non-woven fabric, they offer excellent fluid resistance and structural integrity without compromising on softness. The generously sized 240 × 70 cm sheets are easy to deploy and dispose of, making room turnovers swift and efficient. This convenient 10-pack is an indispensable asset for fast-paced medical practices, hospitals, and allied health clinics seeking high standards of infection control.',
    specs: [
      { label: 'Dimensions', value: '240 × 70 cm', detail: '' },
      { label: 'Material', value: 'Non-Woven', detail: '' },
      { label: 'Color', value: 'Dark Blue', detail: '' },
      { label: 'Pack Size', value: '10 Pack', detail: '' },
    ],
    certifications: ['CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/exam_bed_sheet_10.webp',
    featured: true,
  },
  {
    id: 'exam-couch-hilo',
    name: 'Premium Hi-Lo Examination Couch',
    sku: 'EX-COUCH-HL',
    price: 1549.00,
    priceLabel: '$1,549.00',
    category: 'Furniture and Patient Transfer',
    artgNumber: 'ARTG 203847',
    liveStock: 12,
    tagline: 'Premium examination couch delivering exceptional versatility and comfort.',
    description: 'The Premium Hi-Lo Examination Couch is meticulously engineered with two motorised controls to deliver exceptional versatility, comfort, and functionality for modern clinical environments. Featuring a well-designed two-section layout with adjustable head and seat sections, this couch allows for precise and ergonomic positioning during examinations, treatments, and allied health procedures. The state-of-the-art hi-lo electric lift significantly enhances accessibility for practitioners and patients alike, effectively reducing manual lifting strains and improving overall clinic workflow. Upholstered in an easy-to-clean, medical-grade navy blue vinyl, the couch strongly supports infection control and daily sanitation routines. A highly robust steel frame combined with smooth, lockable castors ensures unparalleled stability and effortless movement between different treatment areas, making it ideal for physiotherapy, general practice, and rehabilitation centres.',
    specs: [
      { label: 'Configuration', value: '2-section', detail: 'For optimal flexibility' },
      { label: 'Padding Thickness', value: '5cm', detail: '' },
      { label: 'Motorisation', value: 'Single motor', detail: 'For hi-lo and back adjustments' },
      { label: 'Width', value: '70cm', detail: 'Generous space for patient comfort' },
      { label: 'Upholstery', value: 'Heavy-duty PVC vinyl', detail: 'Fire, stain, mildew, oil, water, and wear-resistant' },
    ],
    certifications: ['ISO 13485', 'CE Mark'],
    image: '/images/exam_couch.webp',
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    featured: true,
  },
  {
    id: 'exam-gown-regular',
    name: 'Disposable Gowns',
    sku: 'EX-GOWN-REG',
    price: 3.99,
    priceLabel: '$3.99',
    category: 'Infection Prevention',
    artgNumber: 'ARTG 394857',
    liveStock: 1500,
    tagline: 'Comfort, hygiene, and functionality for medical environments.',
    description: 'The Patient Gown offers a perfect combination of comfort, hygiene, and functionality, thoughtfully designed to meet the rigorous demands of fast-paced medical environments. Crafted with patient care as the utmost priority, these gowns provide essential coverage and modesty during comprehensive medical examinations, diagnostic procedures, and treatments. They are manufactured from a remarkably soft, breathable, non-woven material that ensures maximum comfort while remaining highly durable and effective for single-use applications. The intuitive design features secure waist ties and accommodating shoulder sleeves that offer a highly adjustable fit, catering to a wide and diverse range of patient body types. Designed strictly for one-time use, this high-quality gown is instrumental in reducing the risk of cross-contamination and upholding pristine clinical hygiene standards.',
    specs: [
      { label: 'Size', value: 'Regular (105 cm x 140 cm)', detail: '' },
      { label: 'Color', value: 'Dark blue', detail: '' },
      { label: 'Material', value: 'Breathable non-woven fabric', detail: '' },
      { label: 'Type', value: 'Single-Use', detail: '' },
    ],
    certifications: ['CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/patient_examination_gown.webp',
  },
  {
    id: 'thermasonic-gel-warmer',
    name: 'Ultrasound Gel warmer',
    sku: 'TG-WARM-01',
    price: 245.00,
    priceLabel: '$245.00',
    category: 'Medical Equipment',
    artgNumber: 'ARTG 495823',
    liveStock: 45,
    tagline: 'Rapidly and safely heat ultrasound gel to optimal temperatures.',
    description: 'The Thermasonic Gel Warmer is a widely trusted and indispensable ultrasound gel warmer specifically designed to rapidly and safely heat ultrasound gel to optimal patient temperatures. Highly ideal for medical professionals across diverse healthcare settings, this medical-grade gel warmer features an exceptionally durable construction and reliable performance that ensures consistent, day-long gel warming. Available in versatile single-bottle, multi-bottle, and 20-gram packette configurations, each robust unit quickly brings gel to the desired temperature while maintaining precise, microprocessor-driven temperature control. Built with stringent safety standards in mind, it incorporates a critical thermal cutoff mechanism to strictly prevent overheating, alongside a hospital-grade plug. With highly versatile wall-mount or countertop placement options, the Thermasonic Gel Warmer is an essential tool for boosting clinical efficiency and patient satisfaction.',
    specs: [
      { label: 'Heating', value: 'Rapid', detail: 'Powerful element brings gel to desired temperature quickly' },
      { label: 'Control', value: 'Microprocessor', detail: 'Maintains constant temperature' },
      { label: 'Safety', value: 'Thermal cutoff', detail: 'Protection from overheating' },
      { label: 'Power Cord', value: 'Hospital-grade plug', detail: '' },
      { label: 'Construction', value: 'High-density composite', detail: 'Impact-resistant' },
    ],
    certifications: ['UL Listed', 'CSA Listed', 'CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/thermasonic_gel_warmer.webp',
    featured: true,
  },
  {
    id: 'med-warming-cabinet',
    name: 'Medical Warming Cabinet',
    sku: 'MWC-PRO-1',
    price: 4390.00,
    priceLabel: '$4,390.00',
    category: 'Medical Equipment',
    artgNumber: 'ARTG 592837',
    liveStock: 5,
    tagline: 'Advanced thermal care for blankets and IV fluids.',
    description: 'Our premium medical warming cabinet is meticulously engineered to safely, evenly, and precisely warm essential clinical items such as hospital blankets, intravenous (IV) fluids, and critical irrigation solutions. This advanced thermal care unit is absolutely vital for preventing life-threatening patient hypothermia and maximizing overall comfort during extensive surgical procedures or post-operative recovery. It features highly intuitive, adjustable temperature controls complete with a clear digital display, guaranteeing that optimal thermal conditions are constantly monitored and strictly maintained. The cabinet is constructed from incredibly robust, premium hospital-grade stainless steel that not only guarantees longevity but also facilitates effortless and thorough infection control protocols. Designed to seamlessly integrate into any busy clinical environment, this warming cabinet is a cornerstone of modern, compassionate patient care.',
    specs: [
      { label: 'Material', value: 'Hospital-grade stainless steel', detail: '' },
      { label: 'Control', value: 'Digital display', detail: 'Adjustable temperature controls' },
      { label: 'Application', value: 'Blankets, IV fluids, Irrigation', detail: '' },
    ],
    certifications: ['ISO 13485', 'CE Mark'],
    stockStatus: 'Limited Stock',
    bulkOrderAvailable: true,
    image: '/images/medical_warming_cabinet.webp',
  },
  {
    id: 'mri-safe-wheelchair',
    name: 'MR SAFE Non-Metal Wheelchair',
    sku: 'MRI-WC-NM',
    price: 3200.00,
    priceLabel: '$3,200.00',
    category: 'Furniture and Patient Transfer',
    artgNumber: 'ARTG 684732',
    liveStock: 8,
    tagline: 'Specially designed MR SAFE patient transport device without any metal parts.',
    description: 'This uniquely engineered, 100% non-metal wheelchair is specially designed as an uncompromising MR SAFE patient transport device for demanding use in busy hospitals and sensitive MR laboratories. Constructed entirely from durable, recyclable plastic with absolutely no metal or loose parts, it guarantees zero interference with complex, high-field MRI diagnostic equipment. Its highly ergonomic form was carefully developed within a therapeutic professional environment to provide unmatched comfort, a remarkably wide seat area, and extraordinary stability for the patient. Approved for safely transporting users up to 150 kg, it drastically eases the physical workload of MRI technicians and hospital porters through incredibly easy and smooth maneuvering. Fully approved according to rigorous EN12183 and ISO 7176 standards, this maintenance-free wheelchair is the ultimate solution for seamless patient transit across the entire hospital facility and into the MRI room.',
    specs: [
      { label: 'Materials', value: 'Rotomolded PE', detail: 'Body and footrest' },
      { label: 'Tyres', value: 'PU tubeless', detail: 'Nylon rims' },
      { label: 'Weight Capacity', value: 'Up to 150 kg', detail: '' },
      { label: 'Maintenance', value: 'Zero maintenance', detail: 'No loose or metal parts' },
    ],
    certifications: ['EN12183', 'ISO 7176'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/non_metal_wheelchair.webp',
    featured: true,
  },
  {
    id: 'sony-upp-110hg',
    name: 'Sony UPP-110HG Thermal paper',
    sku: 'SNY-UPP-110HG',
    price: 24.50,
    priceLabel: '$24.50',
    category: 'Medical Imaging Consumables',
    artgNumber: 'ARTG 748392',
    liveStock: 420,
    tagline: 'A6 width black and white high density glossy print media (type II).',
    description: 'The Sony UPP-110HG (or UPP110HG) is an industry-leading, A6 width black and white high-density glossy print media (Type II) designed explicitly for premium ultrasound diagnostic applications. Each roll of this authentic Sony UPP-110HG print media meticulously measures 110mm in width by 18m in length, boasting a high-yield capacity that can reliably achieve up to 195 high-resolution diagnostic prints. Formulated to produce remarkably sharp, high-contrast, and smudge-resistant grayscale images, it significantly assists clinicians in accurate morphological assessments and reporting. This specialized thermal paper ensures broad, seamless compatibility with a vast array of popular Sony thermal printers, including the UP-X898MD, UP-D898MD, UP-897MD, UP-D897, UP-895, UP-D895, UP-890, UP-D890, UP-860, and UP-D860 models. Trust in genuine Sony media to protect your printer\'s sensitive thermal head while delivering consistently flawless clinical imagery.',
    specs: [
      { label: 'Dimensions', value: '110mm x 18m', detail: '' },
      { label: 'Capacity', value: 'Up to 195 prints', detail: '' },
      { label: 'Type', value: 'High density glossy (Type II)', detail: '' },
      { label: 'Format', value: 'A6 width', detail: '' },
    ],
    certifications: ['CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/sony_upp_110hg_print_media.webp',
  },
  {
    id: 'tisora-facial-tissue',
    name: 'Tisora Facial Tissue',
    sku: 'TSR-FT-2PLY',
    price: 2.20,
    priceLabel: '$2.20',
    category: 'Everyday Paper Supplies',
    artgNumber: 'ARTG 839201',
    liveStock: 800,
    tagline: 'Premium, ultra-soft, and highly absorbent 2-ply facial tissues.',
    description: 'Tisora Facial Tissues represent the pinnacle of premium, ultra-soft, and highly absorbent 2-ply tissue design, crafted specifically for demanding healthcare environments. Thoughtfully formulated for superior patient comfort and impeccable hygiene, they are an essential addition to any clinical examination room, patient ward, or busy reception waiting area. Manufactured with hypoallergenic properties, these tissues are remarkably gentle on even the most sensitive, compromised skin, significantly reducing the risk of irritation or allergic reactions. Despite their luxurious softness, they boast exceptional structural strength and absorbency to reliably handle daily clinical use, spills, and patient needs without tearing or disintegrating prematurely. Choosing Tisora ensures that you are providing a soothing, high-quality touch that actively demonstrates your facility\'s profound commitment to patient care and meticulous attention to detail.',
    specs: [
      { label: 'Ply', value: '2-ply', detail: '' },
      { label: 'Attributes', value: 'Ultra-soft, Highly absorbent', detail: '' },
      { label: 'Suitability', value: 'Hypoallergenic', detail: '' },
    ],
    certifications: ['FSC Certified'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/tisora_facial_tissue.webp',
  },
  {
    id: 'tisora-toilet-tissue',
    name: 'Tisora Toilet Tissue Paper',
    sku: 'TSR-TT-PRO',
    price: 1.80,
    priceLabel: '$1.80',
    category: 'Everyday Paper Supplies',
    artgNumber: 'ARTG 948293',
    liveStock: 1200,
    tagline: 'High-quality, durable and soft toilet tissue paper for healthcare facilities.',
    description: 'Tisora Toilet Tissue Paper is a high-quality, exceptionally durable, and comfortably soft tissue solution purposefully engineered for the unique demands of healthcare facilities and clinical restrooms. Designed with uncompromising standards, it reliably provides maximum hygiene, impressive absorbency, and a reassuring level of comfort for patients and staff alike. Crucially, this tissue is intelligently manufactured to ensure rapid, complete disintegration upon flushing, effectively preventing costly plumbing issues and facility blockages even in high-traffic environments. It successfully balances this essential rapid-breakdown property with a strong, tear-resistant performance during use, ensuring a consistently hygienic and premium experience. Stocking Tisora guarantees that your clinical washrooms maintain the highest possible standards of operational reliability, cleanliness, and thoughtful patient comfort.',
    specs: [
      { label: 'Attributes', value: 'Durable, Soft, Absorbent', detail: '' },
      { label: 'Design', value: 'Quick disintegration', detail: 'Prevents plumbing issues' },
    ],
    certifications: ['FSC Certified'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/tisora_toilet_tissue_paper.webp',
  },
  {
    id: 'ultra-med-roll',
    name: 'Ultra Medical Roll',
    sku: 'UMR-2PLY-25',
    price: 8.50,
    priceLabel: '$8.50',
    category: 'Everyday Paper Supplies',
    artgNumber: 'ARTG 192837',
    liveStock: 650,
    tagline: '2 ply, 25 cm × 50 m medical roll for general clinic use.',
    description: 'The Ultra Medical Roll is an exceptional, versatile clinic consumable featuring 2-ply construction, measuring an expansive 25 cm × 50 m, and providing 150 precisely perforated, easy-tear sheets. It is uncompromisingly manufactured from 100% premium virgin wood pulp, actively avoiding recycled fibres to guarantee a flawlessly clean, remarkably hygienic, and consistently absorbent paper surface on absolutely every sheet. Specifically designed for the rigours of diagnostic environments, it boasts the strength to efficiently lift thick ultrasound gel in a single, clean pass without shredding or leaving residue behind. Beyond ultrasound applications, its robust absorbency makes it incredibly versatile and highly suitable for hygienic hand drying, rapid spill management, and a multitude of general clinical wipe-down tasks. Proudly supplied and supported Australia-wide, this high-capacity medical roll is an indispensable asset for maintaining pristine clinical workflows.',
    specs: [
      { label: 'Dimensions', value: '25 cm × 50 m', detail: '' },
      { label: 'Sheets', value: '150 perforated sheets', detail: '' },
      { label: 'Ply', value: '2 ply', detail: '' },
      { label: 'Material', value: '100% virgin wood pulp', detail: '' },
    ],
    certifications: ['CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/ultra_medical_roll.webp',
    featured: true,
  },
  {
    id: 'us-gel-5l',
    name: 'Ultrasound Gel 5L',
    sku: 'US-GEL-5L',
    price: 28.00,
    priceLabel: '$28.00',
    category: 'Medical Imaging Consumables',
    artgNumber: 'ARTG 283948',
    liveStock: 140,
    tagline: 'Acoustically correct, hypoallergenic ultrasound gel in a 5L bulk container.',
    description: 'Our premium 5-Litre Ultrasound Gel is a highly formulated, acoustically correct contact medium designed to deliver spectacularly clear, optimal imaging performance across the broad spectrum of frequencies used in modern medical ultrasound. This meticulously crafted, high-viscosity gel features absolutely no artificial fragrances or added colours, which ensures unobstructed visibility for the sonographer while drastically reducing the risk of skin irritation for highly sensitive patients. It is thoroughly hypoallergenic, entirely water-soluble, and remarkably easy to clean, guaranteeing that it will never stubbornly stain patient clothing or inflict costly damage upon sensitive ultrasound transducer arrays. Manufactured completely free from formaldehyde and parabens, it is safely bacteriostatic and profoundly non-irritating, actively minimizing harmful bacterial growth. Suitable for repeated, high-volume use in busy diagnostic centres, it is the ultimate, economical choice for prioritizing flawless imaging and total patient safety.',
    specs: [
      { label: 'Volume', value: '5L', detail: '' },
      { label: 'Attributes', value: 'No Fragrance, No Color', detail: 'Hypoallergenic' },
      { label: 'Properties', value: 'Water Soluble', detail: 'Easy to clean, won\'t stain' },
      { label: 'Safety', value: 'No Formaldehyde, Paraben-Free', detail: '' },
    ],
    certifications: ['ISO 13485'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/ultrasound_gel_5L.webp',
    featured: true,
  },
  {
    id: 'us-gel-250ml',
    name: 'Ultrasound Gel 250ML',
    sku: 'US-GEL-250',
    price: 4.50,
    priceLabel: '$4.50',
    category: 'Medical Imaging Consumables',
    artgNumber: 'ARTG 374829',
    liveStock: 800,
    tagline: 'Acoustically correct, hypoallergenic ultrasound gel in a convenient 250ml bottle.',
    description: 'Experience unparalleled acoustic transmission with our premium Ultrasound Gel, conveniently packaged in an ergonomic 250ML dispenser bottle for rapid, precise application during diagnostic procedures. This high-performance gel is scientifically formulated to be acoustically correct, delivering exquisitely clear and flawlessly sharp imaging results across the incredibly broad range of frequencies utilised in contemporary medical ultrasound equipment. It intentionally contains zero artificial fragrances or harsh colorants, ensuring pristine optical clarity and drastically reducing the potential for allergic reactions or uncomfortable skin irritation in sensitive patient demographics. The formulation is exceptionally gentle on the skin, highly water-soluble for effortless post-procedure cleanup, and guaranteed free from harsh chemicals like formaldehyde and parabens. Being inherently bacteriostatic and profoundly non-irritating, this convenient ultrasound gel actively champions uncompromising patient safety, supreme comfort, and flawless diagnostic accuracy in every single scan.',
    specs: [
      { label: 'Volume', value: '250ML', detail: '' },
      { label: 'Attributes', value: 'No Fragrance, No Color', detail: 'Hypoallergenic' },
      { label: 'Properties', value: 'Water Soluble', detail: 'Easy to clean' },
      { label: 'Safety', value: 'Paraben-Free, Bacteriostatic', detail: '' },
    ],
    certifications: ['ISO 13485'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/ultrasound_gel_250ML.webp',
  },
  {
    id: 'uv-probe-disinfector',
    name: 'UV-C LED Ultrasound Probe Disinfector',
    sku: 'VDS-UVC-PD',
    price: 8900.00,
    priceLabel: '$8,900.00',
    category: 'Medical Equipment',
    artgNumber: 'ARTG 485923',
    liveStock: 15,
    tagline: 'High-level disinfection using light, not chemistry.',
    description: 'The VDS UV-C LED Ultrasound Probe Disinfector revolutionizes clinical hygiene by delivering lightning-fast, extremely high-level disinfection utilizing the sheer power of targeted ultraviolet light, entirely bypassing the need for harsh, expensive, and messy chemical agents. The exceptionally intuitive workflow requires only that the clinician load the contaminated probe, securely close the robust chamber, and press a button to initiate a rapid, highly effective automated cycle. This cutting-edge, environmentally conscious device operates with absolutely no costly chemical cartridges, no wasteful hazardous wipes, leaves zero toxic residue on the probe, is completely 100% mercury-free, and requires zero specialized room ventilation. Its advanced, multi-directional UV-C LED arrays deliver a comprehensive, low-temperature, shadow-free germicidal irradiation, ensuring the absolute safest operating environment for both the delicate transducer electronics and the clinical staff. Proudly supplied and comprehensively supported Australia-wide, it guarantees a seamless, remarkably cost-effective, and exceptionally swift probe turnaround between patient examinations.',
    specs: [
      { label: 'Technology', value: 'UV-C LED', detail: 'Multi-directional, mercury-free' },
      { label: 'Process', value: 'Chemical-free', detail: 'No cartridges, no wipes, no residue' },
      { label: 'Operation', value: 'Low temperature', detail: '' },
      { label: 'Ventilation', value: 'Not required', detail: '' },
    ],
    certifications: ['ISO 13485', 'CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/ultrasound_probe_disinfector.webp',
    featured: true,
  },
  {
    id: 'xray-protective-apron',
    name: 'Xray Lead Protective Gown',
    sku: 'XR-APRON-XL',
    price: 295.00,
    priceLabel: '$295.00',
    category: 'Medical Imaging Consumables',
    artgNumber: 'ARTG 592038',
    liveStock: 60,
    tagline: '0.5 mm Pb equivalent front protection in XL format.',
    description: 'This remarkably high-quality, premium X-Ray Protective Apron is meticulously engineered to provide exceptional, uncompromising 0.5 mm Pb (lead) equivalent front radiation shielding for clinicians and technicians operating in hazardous imaging environments. Generously sized in an XL format measuring 1100 × 650 mm, it ensures expansive, reliable coverage of critical torso areas without dangerously restricting necessary mobility or workflow efficiency. It features an incredibly intelligent, ergonomic cross-over back strap design that strategically distributes the considerable weight of the heavy shielding across both broad shoulders instead of the vulnerable neck, drastically reducing long-term musculoskeletal fatigue during lengthy procedures. The apron includes highly secure, quick-release hook-and-loop side closures for a customized, snug fit, a practical sleeveless cut granting total freedom of arm movement, and a highly convenient, built-in chest pocket specifically designed for a personal radiation dosimeter. Encased in a highly durable, instantly wipe-clean coated external shell, it maintains flawless clinical hygiene while offering absolutely formidable, long-lasting radiation defense.',
    specs: [
      { label: 'Protection', value: '0.5 mm Pb equivalent', detail: '' },
      { label: 'Dimensions', value: '1100 × 650 mm (XL)', detail: '' },
      { label: 'Design', value: 'Cross-over back straps', detail: 'Reduces neck fatigue' },
      { label: 'Features', value: 'Chest pocket, Wipe-clean shell', detail: '' },
    ],
    certifications: ['CE Mark'],
    stockStatus: 'In Stock',
    bulkOrderAvailable: true,
    image: '/images/x_ray_protective_apron.webp',
    featured: true,
  }
];

mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    console.log('Connected to MongoDB for seeding');
    await Product.deleteMany({});
    console.log('Cleared existing products');
    await Product.insertMany(products);
    console.log('Inserted products successfully');
    mongoose.connection.close();
  })
  .catch(err => {
    console.error('Error seeding data:', err);
    mongoose.connection.close();
  });
